name: Format

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Add Tool
      run: rustup component add rustfmt
    - name: Check Format
      run: cargo fmt -- --check
