name: Build

on: [push, pull_request]

jobs:
  build:
    env:
        TARGET: thumbv6m-none-eabi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add Target
      run: rustup target add ${TARGET}
    - name: Build
      run: cargo build --verbose --target=${TARGET}
